import type { ProfileField } from '../types'

export const PROFILE_FIELDS: ProfileField[] = [
  { name: 'firstName', label: 'Имя', type: 'text', value: '' },
  { name: 'lastName', label: 'Фамилия', type: 'text', value: '' },
  { name: 'nickname', label: 'Никнейм', type: 'text', value: '' },
  { name: 'email', label: 'Email', type: 'text', value: '' },
  { name: 'age', label: 'Возраст', type: 'number', value: 0 },
  { name: 'experience', label: 'Опыт (лет)', type: 'number', value: 0 },
  { name: 'bio', label: 'О себе', type: 'textarea', value: '' },
  { name: 'goals', label: 'Цели обучения', type: 'textarea', value: '' },
  { name: 'birthDate', label: 'Дата рождения', type: 'date', value: '' },
  { name: 'startDate', label: 'Дата начала обучения', type: 'date', value: '' },
  {
    name: 'country',
    label: 'Страна',
    type: 'select',
    value: '',
    options: ['Россия', 'США', 'Германия', 'Франция', 'Япония'],
  },
  {
    name: 'level',
    label: 'Уровень английского',
    type: 'select',
    value: '',
    options: ['A1', 'A2', 'B1', 'B2', 'C1', 'C2'],
  },
  {
    name: 'gender',
    label: 'Пол',
    type: 'radio',
    value: '',
    options: ['М', 'Ж'],
  },
  {
    name: 'theme',
    label: 'Тема оформления',
    type: 'radio',
    value: '',
    options: ['Светлая', 'Тёмная'],
  },
  {
    name: 'interests',
    label: 'Интересы',
    type: 'checkbox',
    value: [],
    options: ['Спорт', 'Музыка', 'Кино', 'Путешествия', 'IT'],
  },
  {
    name: 'topics',
    label: 'Любимые темы карточек',
    type: 'checkbox',
    value: [],
    options: ['Basics', 'Motivation', 'Humor', 'Cars', 'Sports', 'Village'],
  },
  {
    name: 'notifications',
    label: 'Уведомления',
    type: 'checkbox',
    value: [],
    options: ['Email', 'Push', 'SMS'],
  },
  { name: 'city', label: 'Город', type: 'text', value: '' },
  {
    name: 'language',
    label: 'Родной язык',
    type: 'select',
    value: '',
    options: ['Русский', 'Английский', 'Немецкий', 'Другой'],
  },
  { name: 'about', label: 'Дополнительно', type: 'textarea', value: '' },
]